version: "3.9"
services:
  app:
    build: "."
    command:
      - ""
    depends_on:
      - "postgres"
    ports:
      - "3000"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5436:5432"
