version: "3.9"
services:
  app:
    build: .
    image: vojnic/efpractice2:review
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000"
    environment:
      - pUrl=postgres://postgres:postgres@host.docker.internal:5432/postgres?sslmode=disable
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

